### ISSUE TITLE
"NOAUTH Authentication required" upgrading to Lettuce 6.4.1

### ISSUE THREAD

**Issue by snicoll** [redis/lettuce#3104]
#### Current Behavior

A number of Spring Boot users upgrading to Spring Boot 3.4.x [are reporting](https://github.com/spring-projects/spring-boot/issues/43609) that the upgrade broke their redis-based app. They also reported that upgrading from Lettuce `6.4.1.RELEASE` to Lettuce `6.5.1.RELEASE` fixed their problem.

#### Additional context

I am a Spring Boot maintainer and I am looking for a solution for our 3.4 line. Would downgrading to Lettuce `6.4.0.RELEASE` be an option (it doesn't sound like it would). Upgrading to a new feature release is not something we do in a maintenance release so I was hoping a `6.4.2.RELEASE` with the fix that wasn't backported.

**Comment by tishun** [comment]
Greetings @snicoll,

This issue is quite probably what is described in #2996 and was [supposed to be fixed in the 6.4.1 line too](https://github.com/redis/lettuce/issues/2996#issuecomment-2450020840), but seems to have been left out of the release. I will port it today and release it with 6.4.2.RELEASE, apologies for the confusion.
